# Generated by Django 3.1.3 on 2021-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuserprofile',
            name='education',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
