# Generated by Django 3.1.3 on 2021-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0003_superuserprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuserprofile',
            name='experiance',
            field=models.TextField(null=True),
        ),
    ]
