# Generated by Django 3.1.3 on 2021-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0004_superuserprofile_experiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='govermentuserprofile',
            name='Position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='govermentuserprofile',
            name='education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='govermentuserprofile',
            name='experiance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='govermentuserprofile',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
