# Generated by Django 3.1.3 on 2021-02-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0005_auto_20210224_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govermentuserprofile',
            name='Position',
        ),
    ]
