# Generated by Django 3.1.3 on 2021-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0006_remove_govermentuserprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuserprofile',
            name='experiance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organizationuserprofile',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationuserprofile',
            name='total_project',
            field=models.IntegerField(null=True),
        ),
    ]
