# Generated by Django 3.1.3 on 2021-02-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0008_auto_20210225_1015'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='createproject',
            name='A Complete_Review value is valid between 1 and 10',
        ),
        migrations.AlterField(
            model_name='createproject',
            name='Complete_Review',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
