# Generated by Django 3.1.3 on 2021-02-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0010_auto_20210225_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createproject',
            old_name='Complete_Review',
            new_name='complete_Rating',
        ),
    ]
