# Generated by Django 3.1.3 on 2021-02-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0011_auto_20210225_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='complete_Rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
