# Generated by Django 3.1.3 on 2021-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0012_auto_20210225_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='Complete_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createproject',
            name='assigned_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createproject',
            name='complete_Rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
