# Generated by Django 3.1.3 on 2021-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0015_pastproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuserprofile',
            name='total_project',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
