# Generated by Django 3.1.3 on 2021-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0016_auto_20210228_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='project_progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trackproject',
            name='project_progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
