# Generated by Django 3.1.3 on 2021-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deshboard', '0017_auto_20210228_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastproject',
            name='Complete_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pastproject',
            name='complete_Rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
